### PR TITLE
[ready to publish] oops I forgot the graphic!

### PR DESCRIPTION
**Pull request by slhenry**

### CODE REVIEW

**Comment by yatil** [comment]
@slhenry It would be good if that link had a link text.

**Comment by slhenry** [comment]
What do you suggest?

**Comment by yatil** [comment]
Yes, an alt text would be good. “Introduction to Accessibility – Course” or something.

**Comment by yatil** [comment]
Deploy preview for *wai-news* processing.

Building with commit e08c8ee43c694b7a36a75d5c51f8f1a8a5adaab1

https://app.netlify.com/sites/wai-news/deploys/5dea2db4b86a050008ae0b00

**Pull request merged**
